language: ruby
sudo: false
cache: bundler
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - ruby-head
  - rbx-2
matrix:
  include:
  - rvm: jruby-9.1.4.0
    jdk: oraclejdk7
  - rvm: jruby-9.1.4.0
    jdk: oraclejdk8
  - rvm: jruby-9.1.4.0
    jdk: openjdk7
  - rvm: jruby-head
    jdk: oraclejdk8
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
    - rvm: jruby-head
before_install:
  - gem update --system
  - gem install bundler
  - gem --version
before_script:
  - echo `whereis zip`
  - echo `whereis unzip`
