language: ruby
dist: trusty
cache: bundler
rvm:
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
matrix:
  include:
  - rvm: jruby-9.2
    jdk: openjdk8
  - rvm: jruby-head
    jdk: openjdk8
  - rvm: rbx-4
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-4
    - rvm: jruby-head
before_install:
  - gem --version
before_script:
  - echo `whereis zip`
  - echo `whereis unzip`
env:
  global:
    - JRUBY_OPTS="--debug"
    - COVERALLS_PARALLEL=true
notifications:
  webhooks: https://coveralls.io/webhook
