language: ruby
dist: xenial
cache: bundler
rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
  - truffleruby-head
  - truffleruby
matrix:
  fast_finish: true
  include:
  - rvm: jruby-9.2
    jdk: openjdk8
  - rvm: jruby-9.2
    jdk: openjdk11
  - rvm: jruby-head
    jdk: openjdk11
  - rvm: rbx-4
  - name: Rubocop
    rvm: 2.4
    script:
    - bundle info rubocop
    - bundle exec rubocop
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-4
    - rvm: jruby-head
    - rvm: truffleruby-head
    - rvm: truffleruby
before_install:
  - gem --version
before_script:
  - echo `whereis zip`
  - echo `whereis unzip`
env:
  global:
    - JRUBY_OPTS="--debug"
    - COVERALLS_PARALLEL=true
notifications:
  webhooks: https://coveralls.io/webhook
